//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_SuperMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartProducts
    {
        public int CartProductId { get; set; }
        public int ProductId { get; set; }
        public int Quantity { get; set; }
        public int CartId { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Carts Carts { get; set; }
        public virtual Products Products { get; set; }
    }
}
